### ISSUE TITLE
Rewrite using the heartbeat API

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-afk#10]
aw-watcher-afk is different to aw-window etc. because of how AFK periods are calculated, great care must be taken to ensure we don't make a simplification which departs from the specification/current implementation.

I can come up with these causes of complexity that might need some thinking:

 - When does a user become AFK? When he/she has not interacted for `duration x`. Do we simply avoid sending heartbeats when there is no new activity and then send a heartbeat with a longer `pulsetime` if we're still within the non-AFK window? When he/she actually becomes AFK we need to send a heartbeat with a timestamp that's `duration x` old.
 - ... (there's something more I'm sure)

**Comment by johan-bjareholt** [comment]
This would be very nice. It's the last watcher that depends on replace_last_event

**Comment by ErikBjare** [comment]
@johan-bjareholt Started doing this in 89a2ed9. A PR should be opened.
