### ISSUE TITLE
KeyboardSwitch missing arguments

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-afk#12]
So I was testing it out on Windows today. Worked well for the first 4 minutes and then:

```
TypeError: KeyboardSwitch() missing 8 required positional arguments: 'msg', 'vk_code', 'scan_code', 'ascii', 'flags', 'time', 'hwnd', and 'win_name'
```

Likely an issue in PyUserInput.

**Comment by ErikBjare** [comment]
Found this: https://stackoverflow.com/questions/27363268/how-can-i-avoid-typeerror-mouseswitch-missing-8-required-positional-arguments

Which lead me to: https://stackoverflow.com/questions/26156633/pythoncom-crashes-on-keydown-when-used-hooked-to-certain-applications

Looks like an issue in pyHook

**Comment by ErikBjare** [comment]
I've also gotten a similar error for MouseSwitch:

```
TypeError: MouseSwitch() missing 8 required positional arguments: 'msg', 'x', 'y', 'data', 'flags', 'time', 'hwnd', and 'window_name'
```

**Comment by ErikBjare** [comment]
I've filed a [bug report with relevant links on pyHook's Sourceforge](https://sourceforge.net/p/pyhook/bugs/7/).

**Comment by ErikBjare** [comment]
We might want to use the fork [PyHook3](https://pypi.python.org/pypi/PyHook3) in the meantime.

**Comment by johan-bjareholt** [comment]
> Known bugs
>  - PyInstaller can't build single-file executables using pyHook. This may be fixed in 1.5.1, but hasn't been tested.

This is mentioned on the README.md in the projects github repo, just a precaution

**Comment by ErikBjare** [comment]
I wrote about this in #13 as well, but well... I implemented a basic wrapper for the Windows API GetLastInputInfo in this Gist: https://gist.github.com/ErikBjare/2d7aab90b90b664798b51a83cce7f325

aw-watcher-afk is not written to work with this kind of info (time since last input) but it's likely a far more sane way of handling it than we do currently.

**Comment by ErikBjare** [comment]
The implementation and refactor needed was completed in PR #14

**Comment by LiuLikeQian** [comment]
when fixed this question??
