### ISSUE TITLE
Avoid detecting AFK when watching a video in chrome

### ISSUE THREAD

**Issue by soumyasanyal** [ActivityWatch/aw-watcher-afk#46]
I've just recently started using ActivityWatch and kudos to the team for the awesome work!

I noticed that while watching videos at a stretch, the watcher usually logs AFK, leading to wrong attributions in ActivityWatch (screenshot below). Now, I understand that I'm technically indeed not using my keyboard/mouse which is probably leading to the AFK status. But I wonder if there can be a quick fix to this? Maybe it's possible to have something like an "ignore-domain" list that just ignores using the AFK filter to aggregate results for some specific domains/apps?

![image](https://user-images.githubusercontent.com/14810260/109384139-e0a0bc00-7910-11eb-9e2f-38ed34f73b00.png)

**Comment by ErikBjare** [comment]
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/261, closing.
