### ISSUE TITLE
[bug] aw-watcher-afk over freerdp

### ISSUE THREAD

**Issue by wsdookadr** [ActivityWatch/aw-watcher-afk#52]
I'm using aw-watcher-afk over [freerdp](https://www.freerdp.com/), on Debian 11, but it seems to always report afk.
Tested using xrdp 0.9.12 (server) and xfreerdp 3.0.0-dev 2c31c3675 (client).

**Comment by wsdookadr** [comment]
I managed to find out what the problem was. xrdp uses a separate X display with `DISPLAY=:10` , so I just set that in the associated systemd user unit, in the `[Service]` block, and everything works fine:
```
Environment="DISPLAY=:10"
```
I'm surprised that aw-watcher-window doesn't have the same problem.

**Comment by ErikBjare** [comment]
Hey, nice to see you figured out a solution.

Great work on that guide btw! Mind if I link to it from the [remote server docs](https://docs.activitywatch.net/en/latest/remote-server.html)?

>I'm surprised that aw-watcher-window doesn't have the same problem.

The AFK watcher uses pynput on Linux to check if there's mouse/keyboard activity, while the window watcher polls using python-xlib. According to [pynput docs](https://pynput.readthedocs.io/en/latest/limitations.html#linux), `DISPLAY` must be set.

**Comment by wsdookadr** [comment]
> Mind if I link to it

Feel free to do so :)

> According to pynput docs, DISPLAY must be set

Ah I see now :+1:
