### ISSUE TITLE
document the default `timeout` better

### ISSUE THREAD

**Issue by soxofaan** [ActivityWatch/aw-watcher-afk#55]
I was curious about how aw-watcher-afk detects inactivity (in particular, the time after which "afk" is flagged) and it took me some effort to figure that out.
I eventually I had to dive in the source code  to find out it was 3 minutes: 
https://github.com/ActivityWatch/aw-watcher-afk/blob/af4b59b8bd7a3028f97a94031f60380ded4be488/aw_watcher_afk/config.py#L8

I think it would be useful to document/mention this default `timeout` value, e.g. here:
- https://github.com/ActivityWatch/aw-watcher-afk/blob/master/README.md
- https://docs.activitywatch.net/en/latest/configuration.html
- https://docs.activitywatch.net/en/latest/watchers.html#watchers

**Comment by ErikBjare** [comment]
I agree!

You are very welcome to submit a PR both to https://github.com/ActivityWatch/docs and this repo :)

If you don't have the time, I'll get to it, eventually :)

**Comment by ErikBjare** [comment]
PRs merged, closing.

Thanks @soxofaan! ❤️
